---
title: "ChrisAnalyses"
author: "Chris Stantis"
date: '2022-10-25'
output: html_document
---
```{r setup}
library(tidyverse)
```
 
Let's create a fresh sheet for my notes and analyses. 

#Particle Size
```{r particleSizeImport}
library(readxl)
psdata <- read_excel("ParticleSizeExp1.xlsx")

##Treated Coarse, Analyzed Coarse - Batch 1
B1.CC <- subset(psdata, Tooth=="A"& Treat=="CC" & Analysis=="1")

##Treated Fine, Analyzed Fine - Batch 1
B1.FF <- subset(psdata, Tooth=="A"& Treat=="FF" & Analysis=="1")

##Treated Coarse, Analyzed Fine - Batch 2
B2.CF <- subset(psdata, Tooth=="A"& Treat=="CF" & Analysis=="2")

##Treated Fine, Analyzed Fine - Batch 2
B2.FF <- data.table(filter(psdata,Tooth=="A",Treat=="FF",Analysis=="2"))

##Treated Coarse, Analyzed Coarse - Batch 3
B3.CC <- data.table(filter(psdata,Tooth=="B",Treat=="CC",Analysis=="1"))

##Treated Coarse, Analyzed Fine - Batch 3
B3.CF <- data.table(filter(psdata,Tooth=="B",Treat=="CF",Analysis=="1"))
```

We don't necessarily expect the whole dataset to be normally distributed between the three batches, but it would be ideal to check for normality before running paired t-tests. 

```{r normality}
library(ggpubr)
B1 <- subset(psdata, Tooth == "A" & Analysis == "2")
shapiro.test(B1$dC)
shapiro.test(B1$dO)
shapiro.test(B1$CO3)

B2 <- subset(psdata, Tooth == "A" & Analysis == "2")
shapiro.test(B2$dC)
shapiro.test(B2$dO)
shapiro.test(B2$CO3)
```